version: '3'

services:
  jekyll:
    build: .
    # command: tail -f /dev/null
    command: bundle exec jekyll serve --watch --host=0.0.0.0
    ports:
      - 4000:4000
    volumes:
      - ./:/srv/jekyll
